"""Infrastructure adapters implementing domain-facing persistence and integrations."""

from .action_snapshots import (
    ACTION_SNAPSHOT_CONTENT_SCHEMA_VERSION,
    DeploymentVersionObserver,
    ImmutableActionSnapshotWriter,
)
from .checkpoints import (
    DIAGNOSIS_CHECKPOINT_NAMESPACE,
    ApprovalCheckpointIdentity,
    DiagnosisCheckpointIdentity,
    approval_checkpoint_config,
    diagnosis_checkpoint_config,
    diagnosis_checkpoint_serializer,
    postgres_approval_checkpointer,
    postgres_diagnosis_checkpointer,
)
from .diagnosis_runtime import (
    CheckpointExecutionStatus,
    DiagnosisCheckpointObservation,
    DiagnosisRunOutcome,
    DiagnosisWorkflowRunner,
    checkpoint_observation,
    compiled_diagnosis_runner,
)
from .health_verification import (
    HEALTH_VERIFICATION_COLLECTION_SCHEMA_VERSION,
    MAX_VERIFICATION_COLLECTION_TIMEOUT_SECONDS,
    ActiveVersionBackend,
    ActiveVersionResult,
    ActiveVersionSample,
    CollectedHealthVerification,
    HealthProbeBackend,
    HealthProbeResult,
    HealthProbeSample,
    HealthVerificationCollectionIds,
    HealthVerificationCollectionRequest,
    LiveHealthVerificationCollector,
    NewAlertCountBackend,
    NewAlertCountResult,
    NewAlertCountSample,
)
from .memory_embeddings import DeterministicIncidentMemoryEmbedder
from .mock_model import (
    MOCK_MODEL_VERSION,
    DeterministicDiagnosisMockModel,
    MockDiagnosisRequest,
    MockModelMalformedOutput,
    MockModelRefusal,
    MockModelResult,
    MockModelScenario,
    MockModelTimeout,
)
from .persisted_health_verification import (
    HEALTH_VERIFICATION_DECISION_AUDIT_SCHEMA_VERSION,
    PostgresPersistedHealthVerifier,
)
from .recovery_tools import ROLLBACK_SERVICE_VERSION, rollback_service_definition
from .rollback_adapter import DeploymentRollbackBackend, ServerBoundRollbackAdapter

__all__ = [
    "ACTION_SNAPSHOT_CONTENT_SCHEMA_VERSION",
    "DIAGNOSIS_CHECKPOINT_NAMESPACE",
    "HEALTH_VERIFICATION_COLLECTION_SCHEMA_VERSION",
    "HEALTH_VERIFICATION_DECISION_AUDIT_SCHEMA_VERSION",
    "MAX_VERIFICATION_COLLECTION_TIMEOUT_SECONDS",
    "MOCK_MODEL_VERSION",
    "ROLLBACK_SERVICE_VERSION",
    "ActiveVersionBackend",
    "ActiveVersionResult",
    "ActiveVersionSample",
    "ApprovalCheckpointIdentity",
    "CheckpointExecutionStatus",
    "CollectedHealthVerification",
    "DeploymentRollbackBackend",
    "DeploymentVersionObserver",
    "DeterministicDiagnosisMockModel",
    "DeterministicIncidentMemoryEmbedder",
    "DiagnosisCheckpointIdentity",
    "DiagnosisCheckpointObservation",
    "DiagnosisRunOutcome",
    "DiagnosisWorkflowRunner",
    "HealthProbeBackend",
    "HealthProbeResult",
    "HealthProbeSample",
    "HealthVerificationCollectionIds",
    "HealthVerificationCollectionRequest",
    "ImmutableActionSnapshotWriter",
    "LiveHealthVerificationCollector",
    "MockDiagnosisRequest",
    "MockModelMalformedOutput",
    "MockModelRefusal",
    "MockModelResult",
    "MockModelScenario",
    "MockModelTimeout",
    "NewAlertCountBackend",
    "NewAlertCountResult",
    "NewAlertCountSample",
    "PostgresPersistedHealthVerifier",
    "ServerBoundRollbackAdapter",
    "approval_checkpoint_config",
    "checkpoint_observation",
    "compiled_diagnosis_runner",
    "diagnosis_checkpoint_config",
    "diagnosis_checkpoint_serializer",
    "postgres_approval_checkpointer",
    "postgres_diagnosis_checkpointer",
    "rollback_service_definition",
]
