"""Pure incident-domain contracts and invariants."""

from .errors import (
    DomainError,
    InvalidDomainValueError,
    InvalidIdentifierError,
    InvalidIncidentTransitionError,
    NaiveDateTimeError,
    NonMonotonicTimeError,
    OptimisticVersionError,
)
from .incidents import (
    ALLOWED_TRANSITIONS,
    CANCELLABLE_STATES,
    DEFERRED_CANCELLATION_STATES,
    DURABLE_WAIT_STATES,
    TERMINAL_STATES,
    CancellationDisposition,
    EventMetadata,
    Incident,
    IncidentCancellationRequest,
    IncidentChange,
    IncidentSeverity,
    IncidentState,
    IncidentTransition,
)
from .values import (
    ActorId,
    AggregateVersion,
    AlertId,
    CausationId,
    CorrelationId,
    EventReason,
    IncidentId,
    OpaqueIdentifier,
    as_utc,
    utc_now,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "CANCELLABLE_STATES",
    "DEFERRED_CANCELLATION_STATES",
    "DURABLE_WAIT_STATES",
    "TERMINAL_STATES",
    "ActorId",
    "AggregateVersion",
    "AlertId",
    "CancellationDisposition",
    "CausationId",
    "CorrelationId",
    "DomainError",
    "EventMetadata",
    "EventReason",
    "Incident",
    "IncidentCancellationRequest",
    "IncidentChange",
    "IncidentId",
    "IncidentSeverity",
    "IncidentState",
    "IncidentTransition",
    "InvalidDomainValueError",
    "InvalidIdentifierError",
    "InvalidIncidentTransitionError",
    "NaiveDateTimeError",
    "NonMonotonicTimeError",
    "OpaqueIdentifier",
    "OptimisticVersionError",
    "as_utc",
    "utc_now",
]
